= 关于Neo4j中文手册 =

文档采用了asciidoc格式，请参考：

* http://www.methods.co.nz/asciidoc/
* http://powerman.name/doc/asciidoc

== 编译生成文档 ==

Asciidoc version 8.6.8 is a requirement
together with whatever dependencies it needs
and specifically docbook, w3m, fop and graphviz.

http://maven.apache.org/[Apache Maven] together with http://www.gnu.org/software/make/[Make] are used to unpack the pieces of the manual and to execute asciidoc on them.
Note that running parallel jobs with Make (-j option) is not supported.

生成文档, 使用命令: +
`mvn clean install` +
This will produce a single html5 page (in 'target/html5').
Note that this won't suffice in order to build the download packages of Neo4j.
However, the build requirements are limited to Python and Graphviz (and Maven, Java).
This build checks for missing include files and AsciiDoc syntax errors.

要生成所有的目标, 使用: +
`mvn clean install -DfullBuild`
或者 +
`mvn clean install -DfullManualBuild`

To build all dependencies of the manual, use the following at the top level of the repository: +
`mvn clean install -DdocsBuild` +
In order to build all the artifacts of the manual too, add `-DfullManualBuild`

=== 在OSX系统上面生成文档 ===

安装涉及到的库文件

  brew install docbook asciidoc w3m fop graphviz libtool

注册 docbook xml DTD

  sudo ./osx-register-docbook

=== 在Ubuntu系统上生成文档 ===

  sudo apt-get install asciidoc docbook fop graphviz w3m maven libxml2-utils xsltproc



